In [1]:
ratings=6

In [2]:
if ratings>7:
    print('Movie is superhit')
else:
    print('Movie is not too good')

Movie is not too good


In [3]:
if ratings>8:
    print('Super_Hit')
elif ratings>5 & ratings<8:
    print('Hit')
else:
    print('Flop_Movie')

Hit


In [4]:
num=-1.51

In [5]:
if num==1:
    print('positive number')
elif num>=-1.51:
    print('Negative Number')
else:
    print('Zero')

Negative Number


In [6]:
numbers=[1,2,5,6,8]

In [7]:
num_sum=0

for x in numbers:
    num_sum=num_sum+x
    print(num_sum)

1
3
8
14
22


In [8]:
x=[90,50,60,43,21,70]

In [9]:
for i in x:
    if i>50:
        print('Admission')
    else:
        print('No_Admission')

Admission
No_Admission
Admission
No_Admission
No_Admission
Admission


In [10]:
num=[1,2,3,4,5,6,7,8]
for i in num:
    if i%2==0:
        print('even',i)
    else:
        print('odd',i)

odd 1
even 2
odd 3
even 4
odd 5
even 6
odd 7
even 8


In [11]:
num=[1,2,3,4,5,6,7,8]
for i in num:
    if i%2==0:
        print('even',i)

even 2
even 4
even 6
even 8


In [12]:
num=[1,2,3,4,5,6,7,8]
even_sum=0

for i in num:
    if i%2==0:
        even_sum=1+even_sum
print(even_sum)

4


In [13]:
num=[1,2,3,4,5,6,7,8]
even_sum=0
odd_sum=0

for i in num:
    if i%2==0:
        even_sum+=1
        odd_sum+=1
print(even_sum)
print(odd_sum)

4
4


In [14]:
# While Loop

In [15]:
'''num_input=int(input("enter a number:"))
sum=0
i=1

while i<=num_input:
        sum=sum+i
        i=i+1
print("total sum is",sum)
'''

'num_input=int(input("enter a number:"))\nsum=0\ni=1\n\nwhile i<=num_input:\n        sum=sum+i\n        i=i+1\nprint("total sum is",sum)\n'

In [16]:
#num_input=int(input("enter a number:"))
i=1

while i<=7:
        print(i)
        i=i+1

1
2
3
4
5
6
7


In [17]:
count=0
driver_speed=84
safe_speed=30

while (driver_speed>=safe_speed):
    driver_speed=driver_speed-5
    print('slow the speed')
    count+=1
print(count,driver_speed)

slow the speed
slow the speed
slow the speed
slow the speed
slow the speed
slow the speed
slow the speed
slow the speed
slow the speed
slow the speed
slow the speed
11 29


In [18]:
# Or
speed=84
while speed>=30:
    print('slow your speed')
    speed=speed-5

slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed


In [19]:
s1='INDIA'
for val in s1:
    if val=='D':
        break
    print(val)

I
N


In [20]:
input='This is a python'

for x in input:
    if x=='p':
        break
    print(x)

T
h
i
s
 
i
s
 
a
 


In [21]:
# Functions

In [22]:
# Create a function with add x and y

def add_two_num(x,y):
    sum=x+y
    return sum

In [23]:
add_two_num(12,13)

25

In [24]:
# Create fun add 3 numbers return square of total. print all the numbers
# its sum and square

def add_three(a,b,c):
    return (a+b+c , (a+b+c)**2)
print('Sum and Square of: ',2,3,5,add_three(2,3,5))

Sum and Square of:  2 3 5 (10, 100)


In [25]:
add_three(1,2,4)

(7, 49)

In [26]:
# Fun for derivative of (x+2)^y and evaluate function for f(2,3) & f(4,5)

def derive(x,y):
    s=y*((x+2)**(y-1))
    return s

In [27]:
derive(2,3)

48

In [28]:
derive(1,3)

27

In [29]:
derive(4,5)

6480

In [30]:
'''
 1)Function for sigmoid s(2), s(10) 1/1+exp(-x)
 2)write fun to write a absolute value of entered no.Find abs of 2 & -4
'''

'\n 1)Function for sigmoid s(2), s(10) 1/1+exp(-x)\n 2)write fun to write a absolute value of entered no.Find abs of 2 & -4\n'

In [31]:
import math
def sigmoid(x):
    s=1/(1+math.exp(-x))
    return s

In [32]:
sigmoid(2)

0.8807970779778823

In [33]:
sigmoid(10)

0.9999546021312976

In [34]:
sigmoid(-10)

4.5397868702434395e-05

In [35]:
#print((-7.0).__abs__())

In [36]:
#print((2).__abs__())

In [37]:
#print((-4).__abs__())

In [38]:
def simple_abs(num):
    return -num if num < 0 else num

In [39]:
simple_abs(2)

2

In [40]:
simple_abs(-4)

4

# Pandas

In [41]:
import pandas as pd

In [42]:
d1=[1,2,3,4]

In [43]:
s1=pd.Series(d1)
s1

0    1
1    2
2    3
3    4
dtype: int64

In [44]:
type(s1)

pandas.core.series.Series

In [45]:
s2=pd.Series(d1,index=['a','b','c','d'])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [46]:
df=pd.DataFrame(d1)
df

0
0  1
1  2
2  3
3  4

In [47]:
dict1={'fruit':['Apple','Mango','Orange'],'count':[10,20,30]}
dict1

{'fruit': ['Apple', 'Mango', 'Orange'], 'count': [10, 20, 30]}

In [48]:
df2=pd.DataFrame(dict1,index=['a','b','c'])
df2

fruit  count
a   Apple     10
b   Mango     20
c  Orange     30

In [7]:
import pandas as pd
Ldf=pd.DataFrame({'Alphabet':['a','b','c','d'],
                 'Number':['1','2','3','4'],
                 'Alphanumeric':['a1','b2','c3','d4']},index=['@','#','$','%'])
Ldf

Alphabet Number Alphanumeric
@        a      1           a1
#        b      2           b2
$        c      3           c3
%        d      4           d4

In [8]:
Rdf=pd.DataFrame({'Alphabet':['a','b','c','d'],
                 'Number':['5','6','7','8'],
                 'Alphanumeric':['e1','e2','e3','e4']},index=['!','^','&','*'])
Rdf

Alphabet Number Alphanumeric
!        a      5           e1
^        b      6           e2
&        c      7           e3
*        d      8           e4

In [9]:
mergeddf=pd.merge(Ldf,Rdf,on='Alphabet')
mergeddf

Alphabet Number_x Alphanumeric_x Number_y Alphanumeric_y
0        a        1             a1        5             e1
1        b        2             b2        6             e2
2        c        3             c3        7             e3
3        d        4             d4        8             e4

In [10]:
mergedf=pd.merge(Rdf,Ldf,on='Alphabet')
mergedf

Alphabet Number_x Alphanumeric_x Number_y Alphanumeric_y
0        a        5             e1        1             a1
1        b        6             e2        2             b2
2        c        7             e3        3             c3
3        d        8             e4        4             d4

In [11]:
d1=pd.DataFrame({'Key':['0','1','2','3'],
                'A':['A0','A1','A2','A3']})
d1

Key   A
0   0  A0
1   1  A1
2   2  A2
3   3  A3

In [12]:
d2=pd.DataFrame({'Key':['0','1'],
                'A':['A0','A1']})
d2

Key   A
0   0  A0
1   1  A1

In [13]:
Jdf=d1.join(d2,lsuffix='_first_d1',rsuffix='_second_d2')
Jdf

Key_first_d1 A_first_d1 Key_second_d2 A_second_d2
0            0         A0             0          A0
1            1         A1             1          A1
2            2         A2           NaN         NaN
3            3         A3           NaN         NaN

In [14]:
Jdf1=d1.join(d2,how='outer',lsuffix='_first_d1',rsuffix='_second_d2')
Jdf1

Key_first_d1 A_first_d1 Key_second_d2 A_second_d2
0            0         A0             0          A0
1            1         A1             1          A1
2            2         A2           NaN         NaN
3            3         A3           NaN         NaN

In [15]:
# Cocatenation

In [16]:
c1=pd.DataFrame({'Name':['san','dip','sandy'],
                'Age':[10,11,18]},index=[0,1,2])

In [17]:
c2=pd.DataFrame({'Name':['san1','dip1','sandy1'],
                'Age':[23,24,28]},index=[3,4,5])

In [18]:
c3=pd.DataFrame({'Name':['san2','dip2','sandy2'],
                'Age':[14,19,27]},index=[6,7,8])

In [19]:
c_concat=pd.concat([c1,c2,c3])
c_concat

Name  Age
0     san   10
1     dip   11
2   sandy   18
3    san1   23
4    dip1   24
5  sandy1   28
6    san2   14
7    dip2   19
8  sandy2   27

In [62]:
cars=pd.read_csv(r"C:\Users\Sandip\Cars.csv")
cars.head()

S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   

   gear  carb  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2

In [63]:
cars=cars.rename(columns={'Car_Name':'Model'})
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
S.No          32 non-null int64
Unnamed: 1    32 non-null object
mpg           32 non-null float64
cyl           32 non-null int64
disp          32 non-null float64
hp            32 non-null int64
drat          32 non-null float64
wt            32 non-null float64
qsec          29 non-null float64
vs            32 non-null int64
am            32 non-null int64
gear          32 non-null int64
carb          32 non-null int64
dtypes: float64(5), int64(7), object(1)
memory usage: 3.2+ KB


In [64]:
cars['qsec'].head() 

0    16.46
1    17.02
2    18.61
3    19.44
4    17.02
Name: qsec, dtype: float64

In [65]:
cars['qsec']=cars['qsec'].fillna(cars.qsec.mean())

In [66]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
S.No          32 non-null int64
Unnamed: 1    32 non-null object
mpg           32 non-null float64
cyl           32 non-null int64
disp          32 non-null float64
hp            32 non-null int64
drat          32 non-null float64
wt            32 non-null float64
qsec          32 non-null float64
vs            32 non-null int64
am            32 non-null int64
gear          32 non-null int64
carb          32 non-null int64
dtypes: float64(5), int64(7), object(1)
memory usage: 3.2+ KB


In [67]:
#cars=cars.drop(columns=['S.No'])

In [68]:
#cars.iloc[:,5:]

In [69]:
cars.sort_values(by='mpg',ascending=False)
cars.head()

S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   

   gear  carb  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2

In [70]:
#cars['cyl']>7   Resulting in true and false

In [71]:
cars[cars['cyl']>7]

S.No           Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  \
4      5    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   
6      7           Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   
11    12           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   
12    13           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   
13    14          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   
14    15   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   
15    16  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   
16    17    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   
21    22     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   
22    23          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   
23    24           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   
24    25     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   
28    29       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   
30    31        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   

    am  gear  carb  
4    0     3     2  
6    0     3     4  
11   0     3     3  
12   0     3     3  
13   0     3     3  
14   0     3     4  
15   0     3     4  
16   0     3     4  
21   0     3     2  
22   0     3     2  
23   0     3     4  
24   0     3     2  
28   1     5     4  
30   1     5     8

In [72]:
cars[(cars['cyl']>7) & (cars['hp']>250)]

S.No      Unnamed: 1   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  \
28    29  Ford Pantera L  15.8    8  351.0  264  4.22  3.17  14.5   0   1   
30    31   Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1   

    gear  carb  
28     5     4  
30     5     8

# Numpy

In [73]:
import numpy as np

In [74]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [75]:
print(a)

[1 2 3 4]


In [76]:
q=np.linspace(5,90,20)
q

array([ 5.        ,  9.47368421, 13.94736842, 18.42105263, 22.89473684,
       27.36842105, 31.84210526, 36.31578947, 40.78947368, 45.26315789,
       49.73684211, 54.21052632, 58.68421053, 63.15789474, 67.63157895,
       72.10526316, 76.57894737, 81.05263158, 85.52631579, 90.        ])

In [77]:
# round(q) this round fun is not used with numpy

In [78]:
np.sum([[1,2],[5,6]],axis=1)

array([ 3, 11])

In [79]:
np.sum([[1,2],[5,6]],axis=0)

array([6, 8])

# OOPS

In [80]:
class ClassName:
    v1='I am class attribute'
    def function(self):
        print("I am from inside the class")

In [81]:
obj1=ClassName()

In [82]:
obj1.v1

'I am class attribute'

In [83]:
obj1.function()

I am from inside the class


In [84]:
# Default Constructor

class python:
    v1=''
    def __init__(self):
        self.v1="python class"
    def print_python(self):
        print(self.v1)

In [85]:
obj1=python()

In [86]:
obj1.print_python()

python class


In [87]:
# Example of Method overloading
class human:
    def sayhello(self, name=None):
        if name is not None:
            print('Hello '+name)
        else:
            print('Hello')
# it always go with else part but if u want then get or drop it that is 
# called as the metod overloading

In [88]:
obj=human()

In [89]:
obj.sayhello()

Hello


In [90]:
obj.sayhello('Sandip')

Hello Sandip
