In [1]:
# Que 1)

In [2]:
class BankAccount:
    bal1=0
    
    def check_bal(self):
        print('current balance is:',self.bal1)
    def deposite(self,amt):
        self.bal1 = self.bal1 + amt
    def withdraw(self,wamt):
        if(self.bal1 >= wamt):
            self.bal1 = self.bal1 - wamt
        else:
            print("insufficient account balance")

In [3]:
ob1=BankAccount()

In [4]:
ob1.check_bal()

current balance is: 0


In [5]:
ob1.deposite(2000)

In [6]:
ob1.check_bal()

current balance is: 2000


In [7]:
ob1.withdraw(700)

In [8]:
ob1.check_bal()

current balance is: 1300


In [9]:
# Que 2)

In [10]:
class MinBalAcc(BankAccount):
    MinBal=5000
    
    def withdraw(self,wamt1):
        if(wamt1 > self.MinBal):
            print("minimum balance is:",self.MinBal)
            print("you can not withdraw:",wamt1)

In [11]:
ob2=MinBalAcc()

In [12]:
ob2.withdraw(6000)

minimum balance is: 5000
you can not withdraw: 6000


# Numpy_Asmt

In [13]:
import numpy as np

In [14]:
# Que 1)

np.zeros(25).reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# OR 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# Que 2)
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [17]:
# Que 3)
a=np.arange(10,61,10).reshape(2,3)
a

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
# datatype
a.dtype

dtype('int32')

In [19]:
# Que 4)
s1=np.array((1,2,3))
print(s1)
s2=np.array((4,5,6))
print(s2)

[1 2 3]
[4 5 6]


In [20]:
s1 + s2

array([5, 7, 9])

In [21]:
s1 - s2

array([-3, -3, -3])

In [22]:
s1 * s2

array([ 4, 10, 18])

In [23]:
s1 / s2

array([0.25, 0.4 , 0.5 ])

In [24]:
# Que 5)
s=np.arange(10,91,10).reshape(3,3)
s

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
# extract only 3 rd column
s[:,[2]]

array([[30],
       [60],
       [90]])

In [26]:
# extract only 2 nd row
s[1,:]

array([40, 50, 60])

In [27]:
# intersection of first two Rows and Columns
s[:2,:2]

array([[10, 20],
       [40, 50]])