In [3]:
message='Hello Sandip Python welcomes you !'
print(message)
message='Hello everyone !'
print(message)

Hello Sandip Python welcomes you !
Hello everyone !


In [5]:
# String is just series of characters.Anything written in quotes is 
# considered as a string in python
m1="sandip balaso gundavade"
print(m1.title())

Sandip Balaso Gundavade


In [6]:
print(m1.upper())
print(m1.lower())

SANDIP BALASO GUNDAVADE
sandip balaso gundavade


In [23]:
print("Hello , "+m1.title())

Hello , Sandip Balaso Gundavade


In [25]:
print("Languages:\n\tpython\nJavascript\n\tcpp\n\t\tSandip")

Languages:
	python
Javascript
	cpp
		Sandip


List

In [ ]:
'''list is a collection of elements/items in a particular order. 
not contains single ele. in a list. letters,numbers,alphabets
Square bracket [] used to indicate list. commas to separate individual ele'''
# .pop() removes last ele in list



In [31]:
s1=['maruti','i10','hyundai','honda','hero']
s=s1.pop()
s1

['maruti', 'i10', 'hyundai', 'honda']

In [32]:
s=s1.pop(1)
print(s1)

['maruti', 'hyundai', 'honda']


In [34]:
s1.remove('maruti')
print(s1)

['hyundai', 'honda']


In [5]:
speed=85
i=30

while speed>30:
    speed=speed-5
    print('Slow your speed',speed)

Slow your speed 80
Slow your speed 75
Slow your speed 70
Slow your speed 65
Slow your speed 60
Slow your speed 55
Slow your speed 50
Slow your speed 45
Slow your speed 40
Slow your speed 35
Slow your speed 30


In [7]:
# OR
driver_speed=84
safe_speed=30
count=0
while driver_speed>=safe_speed:
    print('slow your speed')
    driver_speed=driver_speed-5
    count+=1
print(count,driver_speed)

slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
slow your speed
11 29


In [14]:
# create fun .. 3 nos , its addition and square
def add_three(a,b,c):
    return (a+b+c,(a+b+c)**2)
print('numbers and its square:',2,3,5,add_three(2,3,5))

numbers and its square: 2 3 5 (10, 100)


In [19]:
def sqval(a,b,c):
    sum=a+b+c
    return sum,sum**2

In [16]:
sqval(2,3,5)

(10, 100)

In [ ]:
# Merging

In [3]:
import pandas as pd
leftdf=pd.DataFrame({'Alphabet':['a','b','c','d'],
                    'number':[1,2,3,4],
                    'Alphanumeric':['a1','b1','c1','d1']})
leftdf

Alphabet  number Alphanumeric
0        a       1           a1
1        b       2           b1
2        c       3           c1
3        d       4           d1

In [4]:
rightdf=pd.DataFrame({'Alphabet':['a','b','c','d'],
                    'number':[5,6,7,8],
                    'Alphanumeric':['a2','b2','c2','d2']})
rightdf

Alphabet  number Alphanumeric
0        a       5           a2
1        b       6           b2
2        c       7           c2
3        d       8           d2

In [5]:
mergedf=pd.merge(leftdf,rightdf,on='Alphabet')
mergedf

Alphabet  number_x Alphanumeric_x  number_y Alphanumeric_y
0        a         1             a1         5             a2
1        b         2             b1         6             b2
2        c         3             c1         7             c2
3        d         4             d1         8             d2

In [6]:
merge=pd.merge(rightdf,leftdf,on='Alphabet')
merge

Alphabet  number_x Alphanumeric_x  number_y Alphanumeric_y
0        a         5             a2         1             a1
1        b         6             b2         2             b1
2        c         7             c2         3             c1
3        d         8             d2         4             d1

In [8]:
# Joining 
d1=pd.DataFrame({'key':[0,1,2,3],
                'A':['a1','a2','a3','a4']})
d1

key   A
0    0  a1
1    1  a2
2    2  a3
3    3  a4

In [9]:
d2=pd.DataFrame({'key':[4,5],
                'A':['a1','a2']})
d2

key   A
0    4  a1
1    5  a2

In [10]:
joindf=d1.join(d2,lsuffix='_first',rsuffix='_second')
joindf
# By default join is left outer join

key_first A_first  key_second A_second
0          0      a1         4.0       a1
1          1      a2         5.0       a2
2          2      a3         NaN      NaN
3          3      a4         NaN      NaN

In [11]:
joint=d2.join(d1,lsuffix='_first',rsuffix='_second')
joint

key_first A_first  key_second A_second
0          4      a1           0       a1
1          5      a2           1       a2

In [13]:
jd1=d1.join(d2,how='inner',lsuffix='_first',rsuffix='_second')
jd1

key_first A_first  key_second A_second
0          0      a1         4.0       a1
1          1      a2         5.0       a2
2          2      a3         NaN      NaN
3          3      a4         NaN      NaN

In [20]:
jd2=d1.join(d2,how='outer',lsuffix='_first',rsuffix='_second')
jd2

key_first A_first  key_second A_second
0          0      a1         4.0       a1
1          1      a2         5.0       a2
2          2      a3         NaN      NaN
3          3      a4         NaN      NaN

In [21]:
# Concatenation:- It is just adding records ... 
d1=pd.DataFrame({'Name':['john','steve','dark'],
                'Age':[15,12,22]})
d1

Name  Age
0   john   15
1  steve   12
2   dark   22

In [22]:
d2=pd.DataFrame({'Name':['johny','stevy','darky'],
                'Age':[14,18,23]})
d2

Name  Age
0  johny   14
1  stevy   18
2  darky   23

In [23]:
d3=pd.DataFrame({'Name':['jony','stev','darku'],
                'Age':[23,32,41]})
d3

Name  Age
0   jony   23
1   stev   32
2  darku   41

In [26]:
conc=pd.concat([d1,d2,d3])
conc

Name  Age
0   john   15
1  steve   12
2   dark   22
0  johny   14
1  stevy   18
2  darky   23
0   jony   23
1   stev   32
2  darku   41

In [28]:
d1=pd.DataFrame({'Name':['john','steve','dark'],
                'Age':[15,12,22]},index=[1,2,3])
d2=pd.DataFrame({'Name':['johny','stevy','darky'],
                'Age':[14,18,23]},index=[4,5,6])
d3=pd.DataFrame({'Name':['jony','stev','darku'],
                'Age':[23,32,41]},index=[7,8,9])

In [30]:
cocn=pd.concat([d1,d2,d3])
cocn

Name  Age
1   john   15
2  steve   12
3   dark   22
4  johny   14
5  stevy   18
6  darky   23
7   jony   23
8   stev   32
9  darku   41

In [18]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [20]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [21]:
np.linspace(10,50,20)

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

In [22]:
np.random.random((2,3))

array([[0.57405693, 0.44514265, 0.27804895],
       [0.60616046, 0.79503845, 0.21768862]])

In [23]:
np.random.randint(10,25)

11

In [24]:
np.random.randint(10,25,9)

array([21, 22, 11, 20, 18, 18, 11, 19, 23])

In [30]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [31]:
np.size(a)

4

In [32]:
a.shape

(4,)

In [33]:
np.shape(a)

(4,)

In [40]:
b=([[1,2,3,4,5],[6,7,8]])
b

[[1, 2, 3, 4, 5], [6, 7, 8]]

In [38]:
np.size(b)

2

In [41]:
np.shape(b)

(2,)

In [44]:
np.sum([[1,2],[10,9]])

22

In [47]:
np.sum([[1,2],[10,7]],axis=0) # rowise calculation

array([11,  9])

In [48]:
np.sum([[1,2],[10,9]],axis=1) # columnwise calc

array([ 3, 19])

In [49]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [50]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [51]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a[0]

array([1, 2, 3])

In [53]:
a[1,1:]

array([5, 6])

In [55]:
a[:1,1:]

array([[2, 3]])

In [56]:
a[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])