In [5]:
l1=[1,2,3,4,5,6]
l2=[6,5,4,3,2,1]
for i in range(6):
    if l1[i]>l2[i]:
        print('l1 is greater than l2')
    else:
        print('l2 is greater than l1')

l2 is greater than l1
l2 is greater than l1
l2 is greater than l1
l1 is greater than l2
l1 is greater than l2
l1 is greater than l2


In [8]:
t=(10,20,30,40,50)
for i in t:
    i=i+5
    print(i)

15
25
35
45
55


In [13]:
def add_10(x):
    x=x+10
    return x

In [14]:
add_10(25)

35

In [15]:
def check_odd_even(x):
    if x%2==0:
        print(x,'is even')
    else:
        print(x,'is odd')

In [16]:
check_odd_even(27)

27 is odd


In [17]:
# Numpy 5x5 with all zero values
import numpy as np
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# np arr start 10 end 100 with 5 intervals
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [19]:
a=np.arange(10,61,10).reshape(2,3)
a

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
a.size

6

In [26]:
a.dtype

dtype('int32')

In [29]:
a=np.array((1,2,3))
b=np.array((4,5,6))
print(a)
print()
print(b)

[1 2 3]

[4 5 6]


In [32]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [33]:
c=np.arange(10,91,10).reshape(3,3)
c

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [38]:
c[:,[2]]

array([[30],
       [60],
       [90]])

In [39]:
c[1,:]

array([40, 50, 60])

In [45]:
c[:2,:2]

array([[10, 20],
       [40, 50]])

In [46]:
# pandas
import pandas as pd
df=pd.read_csv('insurance.csv')

In [50]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [51]:
df.tail()

age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [52]:
df.shape

(1338, 7)

In [53]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [57]:
df.rename({'bmi':'B_M_I'},axis=1)

age     sex   B_M_I  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [60]:
df.rename(columns={'B_M_I':'bmi'})

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [62]:
df[['age','children','charges']].corr()

age  children   charges
age       1.000000  0.042469  0.299008
children  0.042469  1.000000  0.067998
charges   0.299008  0.067998  1.000000

In [63]:
df.sort_values(by='age',ascending=False)

age     sex     bmi  children smoker     region      charges
335    64    male  34.500         0     no  southwest  13822.80300
603    64  female  39.050         3     no  southeast  16085.12750
752    64    male  37.905         0     no  northwest  14210.53595
1265   64    male  23.760         0    yes  southeast  26926.51440
534    64    male  40.480         0     no  southeast  13831.11520
...   ...     ...     ...       ...    ...        ...          ...
942    18  female  40.185         0     no  northeast   2217.46915
46     18  female  38.665         2     no  northeast   3393.35635
295    18    male  22.990         0     no  northeast   1704.56810
50     18  female  35.625         0     no  northeast   2211.13075
648    18    male  28.500         0     no  northeast   1712.22700

[1338 rows x 7 columns]

In [80]:
a=df.loc[500:1000,{'sex','children','region'}]
a

children     region     sex
500          0  southwest    male
501          0  northeast    male
502          1  southeast    male
503          0  southeast    male
504          1  southeast  female
...        ...        ...     ...
996          3  southwest  female
997          0  southeast  female
998          3  northeast  female
999          0  northwest  female
1000         2  northwest    male

[501 rows x 3 columns]

In [81]:
df.iloc[500:1001,[1,3,5]]

sex  children     region
500     male         0  southwest
501     male         0  northeast
502     male         1  southeast
503     male         0  southeast
504   female         1  southeast
...      ...       ...        ...
996   female         3  southwest
997   female         0  southeast
998   female         3  northeast
999   female         0  northwest
1000    male         2  northwest

[501 rows x 3 columns]

In [82]:
num1=15
num2=23
sum=num1+num2
print('sum of {0} and {1} is {2}'.format(num1,num2,sum))

sum of 15 and 23 is 38


In [83]:
def maxima(a,b):
    if a>=b:
        return a
    else:
        return b

In [85]:
maxima(12,13)

13