In [1]:
import numpy as np

In [2]:
''' Que 1)
5 x 5 matrix with all zeros
'''
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
'''Que 2)
numpy array starting 10 ending 100 with 5 intervals
'''
z1=np.arange(10,101,5)
z1

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [4]:
'''Que 3)
2-D array [10...60] set dimension 2 x 3 
a) print no. of elements in array
b) print data type of array
'''
a1=np.array([10,20,30,40,50,60]).reshape(2,3)
a1

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
a2=np.arange(10,61,10).reshape(2,3)
a2

array([[10, 20, 30],
       [40, 50, 60]])

In [6]:
a2.dtype

dtype('int32')

In [7]:
'''Que 4)
first numpy array values (1,2,3) second array(4,5,6) and perform
1- Addition 2- substraction 3-multiplication 4-division
'''
x=np.array([1,2,3])
y=np.array([4,5,6])

In [8]:
x+y

array([5, 7, 9])

In [9]:
x-y

array([-3, -3, -3])

In [10]:
y-x

array([3, 3, 3])

In [11]:
x*y

array([ 4, 10, 18])

In [12]:
x/y

array([0.25, 0.4 , 0.5 ])

In [13]:
y/x

array([4. , 2.5, 2. ])

In [14]:
'''Que 5)
numpy array 10-90 shape 3 x 3 
a) Extract 3 rd column  b) second row  c)Extract cells at the intersection of
first two rows and first two columns
'''
s1=np.arange(10,91,10).reshape(3,3)
s1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
s1[:,[2]]

array([[30],
       [60],
       [90]])

In [17]:
s1[:,2]

array([30, 60, 90])

In [18]:
s1[1]

array([40, 50, 60])

In [19]:
s1[:2,:2]

array([[10, 20],
       [40, 50]])

In [20]:
s1[0:2,0:2]

array([[10, 20],
       [40, 50]])